### PR TITLE
Updated TaskEstimation file

### PR DESCRIPTION
**Pull request by petedouglas101**
Added Task Estimation Techniques to file

### CODE REVIEW

**Review by erikareilly — COMMENTED** [review]
I think we could change the layout of this. There's a lot of techniques here, may not need to use them all could just give a quick overview of some instead!

**Comment by petedouglas101** [comment]
> I think we could change the layout of this. There's a lot of techniques here, may not need to use them all could just give a quick overview of some instead!

Yeah okay I think you're right. Lets discuss it on our call :)

**Comment by petedouglas101** [comment]
Hey @erikareilly. Are these changes okay?

**Review by erikareilly — APPROVED** [review]
Looks good

**Pull request merged**
